services:
  load-balancer:
    build:
      context: .
      dockerfile: load-balancer/Dockerfile
    container_name: load-balancer
    ports:
      - "9999:9999"
    environment:
      - LB_LISTEN_ADDRESS=0.0.0.0:9999
      - LB_UPSTREAM_ADDRESSES=gateway-1:9000,gateway-2:9001
      - LB_CONNECTIONS_PER_UPSTREAM=600
    networks:
      - internal-network
    depends_on:
      - gateway-1
      - gateway-2
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 40M

  gateway-1: &gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    hostname: gateway-1
    environment: &gateway-environment
      - GATEWAY_LISTEN_ADDRESS=0.0.0.0:9000
      - GATEWAY_QUEUE_URL=queue:6969
      - GATEWAY_QUEUE_CONNECTION_POOL_SIZE=500
      - GATEWAY_RESULT_DIRECTORY=/data/results
    volumes:
      - payment-results:/data/results
    networks:
      - internal-network
    depends_on:
      - queue
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M

  gateway-2:
    <<: *gateway
    hostname: gateway-2
    environment:
      - GATEWAY_LISTEN_ADDRESS=0.0.0.0:9001
      - GATEWAY_QUEUE_URL=queue:6969
      - GATEWAY_QUEUE_CONNECTION_POOL_SIZE=500
      - GATEWAY_RESULT_DIRECTORY=/data/results

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker
    environment:
      - WORKER_QUEUE_URL=queue:6969
      - WORKER_DEFAULT_PROVIDER_URL=http://payment-processor-default:8080
      - WORKER_FALLBACK_PROVIDER_URL=http://payment-processor-fallback:8080
      - WORKER_STRATEGY=greedy
      - WORKER_WORKER_COUNT=100
      - WORKER_PROVIDER_TIMEOUT_MS=5000
      - WORKER_RESULT_DIRECTORY=/data/results
      - WORKER_HEALTH_CHECK_INTERVAL_MS=5500
      - WORKER_FAILURE_SLEEP_MS=100
    volumes:
      - payment-results:/data/results
    networks:
      - internal-network
      - payment-processor
    depends_on:
      - queue
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 70M

  queue:
    build:
      context: .
      dockerfile: queue/Dockerfile
    container_name: queue
    ports:
      - "6969:6969"
    environment:
      - QUEUE_LISTEN_ADDRESS=0.0.0.0:6969
    volumes:
      - queue-data:/data
    networks:
      - internal-network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 40M


networks:
  internal-network:
    driver: bridge
  payment-processor:
    external: true

volumes:
  queue-data:
  payment-results:
