[package]
name = "queue"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.99"
config = "0.15"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["rt-multi-thread", "fs", "io-util", "macros", "net", "sync", "time"] }
